apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
  spec:
    replicas: {{ .Values.deployment.replicas }}
    selector:
      matchlabels:
        app: {{ .Values.deployment.name }}
    templates:
      metadata:
        labels:
          app: {{ .Values.deployment.name }}
        spec: 
          conteiners: 
          - name: {{ .Values.deployment.name }}
            image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
            ports: 
          - containerPort: {{ .Values.deployment.port }}